# Deploys the User Guide to the production
# website whenever master branch is updated
name: Deploy Production

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: /opt/userguide/.github/scripts/deploy.sh
