# https://github.com/NexusPHP/carson/blob/1.x/SUBSCRIBERS.md

version: 1
subscribers:
  - auto-labeler
  - conflicts-notifier
  - pr-title-linter
  - signed-commits
settings:
  auto-labeler:
    sync_labels: true
    rules:
      - label: '4.8' # @todo change value whenever the next minor version is changed
        base_branch: ['^4\.8$']
      - label: github_actions
        files: ['.github/workflows/*']
      - label: documentation
        files:
          all: ['user_guide_src/source/**']
      - label: testing
        files:
          all: ['tests/**']
  conflicts-notifier:
    label: stale
    message: |-
      :wave: Hi, @{{user}}!

      We detected conflicts in your PR against the base branch :speak_no_evil:
      You may want to sync :arrows_counterclockwise: your branch with upstream!

      Ref: [Syncing Your Branch](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#updating-your-branch)
  pr-title-linter:
    name: 'Carson / pr-title-linter'
    rules:
      - pattern: '^(\[\d+\.\d+\]\s{1})?(feat|fix|chore|docs|perf|refactor|style|test|config|revert)(\([\-.@:`a-zA-Z0-9]+\))?!?:\s{1}\S.+\S|Prep for \d\.\d\.\d release|\d\.\d\.\d (Ready|Merge) code$'
        description: 'PR title must include the type (feat, fix, chore, docs, perf, refactor, style, test, config, revert) of the commit per Conventional Commits specification. See https://www.conventionalcommits.org/en/v1.0.0/ for the discussion.'
        level: error
  signed-commits:
    name: 'Carson / signed-commits'
    treat_unsigned_as: failure
