version: 2

updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    groups:
      composer-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/admin/framework'
      - '/admin/starter'
      - '/admin/userguide'
    schedule:
      interval: 'daily'
    groups:
      github-actions:
        patterns:
          - '*'
        group-by: dependency-name
