#!/bin/bash

## Deploy codeigniter4/framework

# Setup variables
SOURCE=$1
TARGET=$2
RELEASE=$3

echo "Preparing for version $3"
echo "Merging files from $1 to $2"

# Prepare the source
cd $SOURCE
git checkout master

# Prepare the target
cd $TARGET
git checkout master

# Copy common files
releasable='app public system writable contributing env license.txt spark .gitignore'
for fff in $releasable ; do
    if [ -d "$fff" ] ; then
        rm -rf $fff
    fi
    cp -Rf ${SOURCE}/$fff ./
done

# Copy framework-specific files
cp -Rf ${SOURCE}/admin/framework/* ./

# Self identify
git config --global user.email "releasebot@codeigniter.com"
git config --global user.name "CodeIgniter Release Bot"
  
# Commit the changes
git add .
git commit -S -m "Release ${RELEASE}"
git push
