<?php

namespace PHPSTORM_META {
    override(\service(), map([
        'autoloader' => \CodeIgniter\Autoloader\Autoloader::class,
        'cache' => \CodeIgniter\Cache\CacheInterface::class,
        'clirequest' => \CodeIgniter\HTTP\CLIRequest::class,
        'codeigniter' => \CodeIgniter\CodeIgniter::class,
        'commands' => \CodeIgniter\CLI\Commands::class,
        'curlrequest' => \CodeIgniter\HTTP\CURLRequest::class,
        'email' => \CodeIgniter\Email\Email::class,
        'encrypter' => \CodeIgniter\Encryption\EncrypterInterface::class,
        'exceptions' => \CodeIgniter\Debug\Exceptions::class,
        'filters' => \CodeIgniter\Filters\Filters::class,
        'format' => \CodeIgniter\Format\Format::class,
        'honeypot' => \CodeIgniter\Honeypot\Honeypot::class,
        'image' => \CodeIgniter\Images\Handlers\BaseHandler::class,
        'iterator' => \CodeIgniter\Debug\Iterator::class,
        'language' => \CodeIgniter\Language\Language::class,
        'locator' => \CodeIgniter\Autoloader\FileLocator::class,
        'logger' => \CodeIgniter\Log\Logger::class,
        'migrations' => \CodeIgniter\Database\MigrationRunner::class,
        'negotiator' => \CodeIgniter\HTTP\Negotiate::class,
        'pager' => \CodeIgniter\Pager\Pager::class,
        'parser' => \CodeIgniter\View\Parser::class,
        'redirectresponse' => \CodeIgniter\HTTP\RedirectResponse::class,
        'renderer' => \CodeIgniter\View\View::class,
        'request' => \CodeIgniter\HTTP\IncomingRequest::class,
        'response' => \CodeIgniter\HTTP\Response::class,
        'router' => \CodeIgniter\Router\Router::class,
        'routes' => \CodeIgniter\Router\RouteCollection::class,
        'security' => \CodeIgniter\Security\Security::class,
        'session' => \CodeIgniter\Session\Session::class,
        'throttler' => \CodeIgniter\Throttle\Throttler::class,
        'timer' => \CodeIgniter\Debug\Timer::class,
        'toolbar' => \CodeIgniter\Debug\Toolbar::class,
        'typography' => \CodeIgniter\Typography\Typography::class,
        'uri' => \CodeIgniter\HTTP\URI::class,
        'validation' => \CodeIgniter\Validation\Validation::class,
        'viewcell' => \CodeIgniter\View\Cell::class,
    ]));
}
