risky: false
linting: true

enabled:
  - align_double_arrow
  - align_equals
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_before_return
  - braces
  - class_definition
  - combine_consecutive_unsets
  - concat_without_spaces
  - elseif
  - encoding
  - full_opening_tag
  - function_declaration
  - function_typehint_space
  - hash_to_slash_comment
  - include
  - lowercase_cast
  - lowercase_constants
  - lowercase_keywords
  - method_argument_space
  - method_separation
  - native_function_casing
  - new_with_braces
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_closing_tag
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_spaces_after_function_name
  - no_spaces_inside_parenthesis
  - no_spaces_inside_offset
  - no_trailing_comma_in_singleline_array
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - no_unneeded_control_parentheses
  - no_unreachable_default_argument_value
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_lines
  - not_operator_with_successor_space
  - object_operator_without_whitespace
  - ordered_imports
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_property
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_single_line_var_spacing
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_types
  - phpdoc_type_to_var
  - print_to_echo
  - psr4
  - self_accessor
  - short_array_syntax
  - short_scalar_cast
  - simplified_null_return
  - single_blank_line_at_eof
  - single_line_after_imports
  - single_quote
  - space_after_semicolon
  - standardize_not_equals
  - switch_case_semicolon_to_colon
  - switch_case_space
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unary_operator_spaces
  - unix_line_endings
  - visibility_required
  - whitespace_after_comma_in_array
