name: PHPUnit

on:
  pull_request:
    branches:
      - develop

jobs:
  main:
    name: Build and test

    strategy:
      matrix:
        php-versions: ['8.2', '8.5']

    runs-on: ubuntu-24.04
    if: (! contains(github.event.pull_request.title, '[ci skip]'))

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer, pecl, phpunit
          extensions: intl, json, mbstring, mysqlnd, xdebug, xml, sqlite3
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-interaction
        # To prevent rate limiting you may need to supply an OAuth token in Settings > Secrets
        # env:
          # https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens
          # COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text
