<?php

echo "<?php

/**
 * Class {$seed_name}
 *
 * Auto-generated by Sprint on {$today}
 */
class {$seed_name} extends Seeder {

    public function run()
    {
        /*
            Here, you can do anything you need to do to get your
            database in the desired state. The following tools are ready for you:

                \$this->ci       // Full CI superobject
                \$this->db       // Database object
                \$this->dbforge  // DatabaseForge instance

            You can split your seeds into multiple files.
            To run them, use the call() method.

                \$this->call('UserSeeder');
         */
    }

    //--------------------------------------------------------------------

}";
