#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php$`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
	oIFS=$IFS
	IFS='
	'
	SFILES="$1"
	IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Starting CodeIgniter precommit..."

if [ "$SFILES" != "" ]
then
	echo "Linting PHP code..."
	for FILE in $SFILES
	do
		php -l -d display_errors=0 "$PROJECT/$FILE"
		if [ $? != 0 ]
		then
			echo "Fix the error(s) before commit."
			exit 1
		fi
		FILES="$FILES $FILE"
	done
fi

if [ "$FILES" != "" ]
then
	echo "Running PHPStan..."
	# Run on whole codebase
	./vendor/bin/phpstan analyse

	if [ $? != 0 ]
	then
		echo "Fix the phpstan error(s) before commit."
		exit 1
	fi
fi

if [ "$FILES" != "" ]
then
	echo "Disaggregating files for PHP-CS-Fixer"
	for FILE in $FILES
	do
		if [[ $FILE == system* ]] # did this match 'system/**'?
		then
			SYSTEM="$SYSTEM $FILE"
		else
			OTHERS="$OTHERS $FILE"
		fi
	done
fi

if [ "$SYSTEM" != "" ]
then
	echo "Running PHP-CS-Fixer on system files"
	./vendor/bin/php-cs-fixer fix --config=system.php_cs.dist --verbose --ansi --using-cache=no $SYSTEM

	if [ $? != 0 ]
	then
		echo "Code style errors fixed in system. Please stage these changes."
		exit 1
	fi
fi

if [ "$OTHERS" != "" ]
then
	echo "Running PHP-CS-Fixer on other PHP files"
	./vendor/bin/php-cs-fixer fix --config=no_header.php_cs.dist --verbose --ansi --using-cache=no $OTHERS

	if [ $? != 0 ]
	then
		echo "Code style errors fixed in other PHP files. Please stage these changes."
		exit 1
	fi
fi

exit 0
