#!/bin/bash

## Build user guide distributable

# Setup variables
. admin/release-config
TARGET=dist/userguide
git checkout $branch

#---------------------------------------------------
echo -e "${BOLD}Build the user guide distributable${NORMAL}"

cp -rf user_guide_src/build/html ${TARGET}/docs
cp -rf user_guide_src/build/epub/* ${TARGET}/

#---------------------------------------------------
# And finally, get ready for merging
echo -e "${BOLD}Assemble the pieces...${NORMAL}"
cd $TARGET
git add .
git commit -S -m "Release ${RELEASE}"
git checkout master
git merge $branch

cd $CI_DIR

#---------------------------------------------------
# Done for now
echo -e "${BOLD}Distributable user guide ready..${NORMAL}"
