#!/bin/bash

## Build app starter distributable

# Setup variables
. admin/release-config
TARGET=dist/appstarter
git checkout $branch

#---------------------------------------------------
echo -e "${BOLD}Build the framework distributable${NORMAL}"

echo -e "${BOLD}Copy the main files/folders...${NORMAL}"
releasable='application public writable README.md contributing.md env license.txt spark'
for fff in $releasable 
    if [ -d $fff ]; then
        rm -rf ${TARGET}/$fff
        cp -rf $fff ${TARGET}/
    else
        rm ${TARGET}/$fff
        cp -f $fff ${TARGET}/
    fi
done

echo -e "${BOLD}Override as needed...${NORMAL}"
cp -rf admin/starter/* ${TARGET}/

echo -e "${BOLD}Fix paths...${NORMAL}"
sed -i "/public $systemDirectory = 'system';/s/'system'/'vendor/codeigniter4/framework/system'/" application/Config/Paths.php

#---------------------------------------------------
# And finally, get ready for merging
echo -e "${BOLD}Assemble the pieces...${NORMAL}"
cd $TARGET
git add .
git commit -S -m "Release ${RELEASE}"
git checkout master
git merge $branch

cd $CI_DIR

#---------------------------------------------------
# Done for now
echo -e "${BOLD}Distributable app starter ready..${NORMAL}"
