#!/bin/bash

## Build framework distributable

# Setup variables
. admin/release-config
TARGET=dist/framework
cd $TARGET
git checkout $branch

#---------------------------------------------------
echo -e "${BOLD}Build the framework distributable${NORMAL}"

echo -e "clean up ${TARGET}";
rm -rf *

echo -e "${BOLD}Copy the main files/folders...${NORMAL}"
releasable='system README.md contributing.md license.txt'
for fff in $releasable ; do
    cp -rf ${CI_DIR}/$fff .
done

echo -e "${BOLD}Override as needed...${NORMAL}"
cp -rf ${CI_DIR}/admin/framework/* .

#---------------------------------------------------
# And finally, get ready for merging
echo -e "${BOLD}Assemble the pieces...${NORMAL}"
git add .
git commit -S -m "Release ${RELEASE}"
git checkout master
git merge $branch

cd $CI_DIR

#---------------------------------------------------
# Done for now
echo -e "${BOLD}Distributable framework ready..${NORMAL}"
