#!/bin/bash

## Build user guide distributable

# Setup variables
. admin/release-config
TARGET=dist/userguide

echo -e "${BOLD}Build the user guide distributable${NORMAL}"

echo -e "${BOLD}Copy the main files/folders...${NORMAL}"
releasable='application public writable README.md contributing.md env license.txt spark'
for fff in $releasable 
    if [ -d $fff ]; then
        rm -rf ${TARGET}/$fff
        cp -rf $fff ${TARGET}/
    else
        rm ${TARGET}/$fff
        cp -f $fff ${TARGET}/
    fi
done

echo -e "${BOLD}Override as needed...${NORMAL}"
cp -rf admin/appstarter/* ${TARGET}/
cp -rf user_guide_src/build/html ${TARGET}/docs

#---------------------------------------------------
# And finally, get ready for merging
cd $TARGET
git add .
git commit -S -m "Release ${RELEASE}"
git checkout master
git merge $branch

cd $CI_DIR

#---------------------------------------------------
# Done for now
echo -e "${BOLD}Distributable user guide ready..${NORMAL}"
