<?php namespace App\Models;

use CodeIgniter\Model;

/**
 * Pepito Model
 *
 * Generated by Vulcan at 2017-09-20 13:12pm
 */
class PepitoModel extends Model
{
    protected $table      = 'categories';
    protected $primaryKey = 'id';

    protected $returnType = 'array';
    protected $useSoftDeletes = false;

    protected $allowedFields = [];

    protected $useTimestamps = false;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $dateFormat    = 'datetime';

    protected $validationRules    = [];
    protected $validationMessages = [];
    protected $skipValidation     = false;
}
