name: Add Labels to PRs

# NOTE: When updating this workflow, you should first change the event to `pull_request` to test the changes
# in a PR, and then change it back to `pull_request_target` before merging.
# @see https://github.com/actions/labeler?tab=readme-ov-file#updating-major-version-of-the-labeler
on:
  - pull_request_target

jobs:
  add-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Verify PR source for workflow file changes
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const prFiles = await github.paginate(github.rest.pulls.listFiles.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            }));
            const workflowFileChanged = prFiles.some(file => file.filename === '.github/workflows/label-pr.yml');

            if (workflowFileChanged) {
              if (context.payload.pull_request.head.repo.full_name !== 'codeigniter4/CodeIgniter4') {
                throw new Error('Changes to label-pr.yml are not allowed from forks.');
              }

              console.log('Workflow file changed, but PR is from the main repository. Proceeding with label addition.');
              return;
            }

            console.log('No changes to workflow file detected, proceeding with label addition.');

      - name: Add labels
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          sync-labels: true # Remove labels when matching files are reverted
