name: Merge develop to next minor branch

on:
  push:
    branches:
      - develop

jobs:
  merge-branch:
    name: Merge develop branch
    if: github.repository_owner == 'codeigniter4'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge branch
        uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: '4.6' # bump when minor version is bumped
          commit_message_template: 'Merge branch ''{source_ref}'' into {target_branch}'
