name: Carson

on:
  pull_request_target:
    types:
      - opened
      - edited

permissions: {}

jobs:
  carson:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Carson
        uses: NexusPHP/carson@62602be15470a18edd31f217b785863e997572d5 # v1.4.0
        with:
          app_id: ${{ secrets.CARSON_APP_ID }}
          private_key: ${{ secrets.CARSON_PRIVATE_KEY }}
          log_level: info
