name: SCSS Compilation

on:
  pull_request:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - '**.scss'
      - '**.css'
      - '.github/workflows/test-scss.yml'

  push:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - '**.scss'
      - '**.css'
      - '.github/workflows/test-scss.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Compilation of SCSS (Node Sass)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          # node version based on dart-sass test workflow
          node-version: 16

      - name: Install sass and node-sass
        run: |
          npm install --global sass node-sass
          sass --version

      - name: Run node-sass
        run: node-sass admin/css/debug-toolbar/toolbar.scss system/Debug/Toolbar/Views/toolbar.css --indent-type space --indent-width 4 --output-style expanded --linefeed lf

      - name: Check for changed CSS files
        run: |
          if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
            echo "Your changes to the SCSS files did not match the expected CSS output."
            git diff-files --patch
            exit 1
          fi
